

final List<String> lista = [
'Mandarin Chinese',
'Spanish',
'English',
'Hindi (sanskritised Hindustani)[9]',
'Bengali',
'Portuguese',
'Russian',
'Japanese',
'Western Punjabi[10]',
'Marathi',
'Telugu',
'Wu Chinese',
'Turkish',
'Korean',
'French',
'German (only Standard German)',
'Vietnamese',
'Tamil',
'Yue Chinese',
'Urdu (persianised Hindustani)[9]',
'Javanese',
'Italian',
'Egyptian Arabic',
'Gujarati',
'Iranian Persian',
'Bhojpuri',
'Min Nan Chinese',
'Hakka Chinese',
'Jin Chinese',
'Hausa',
'Kannada',
'Indonesian (Indonesian Malay)',
'Polish',
'Yoruba',
'Xiang Chinese',
'Malayalam',
'Odia',
'Maithili',
'Burmese',
'Eastern Punjabi[10]',
'Sunda',
'Sudanese Arabic',
'Algerian Arabic',
'Moroccan Arabic',
'Ukrainian',
'Igbo',
'Northern Uzbek',
'Sindhi',
'North Levantine Arabic',
'Romanian',
'Tagalog',
'Dutch',
'Saʽidi Arabic',
'Gan Chinese',
'Amharic',
'Northern Pashto',
'Magahi',
'Thai',
'Saraiki',
'Khmer',
'Chhattisgarhi',
'Somali',
'Malaysian (Malaysian Malay)',
'Cebuano',
'Nepali',
'Mesopotamian Arabic',
'Assamese',
'Sinhalese',
'Northern Kurdish',
'Hejazi Arabic',
'Nigerian Fulfulde',
'Bavarian',
'South Azerbaijani',
'Greek',
'Chittagonian',
'Kazakh',
'Deccan',
'Hungarian',
'Kinyarwanda',
'Zulu',
'South Levantine Arabic',
'Tunisian Arabic',
'Sanaani Spoken Arabic',
'Min Bei Chinese',
'Southern Pashto',
'Rundi',
'Czech',
'Taʽizzi-Adeni Arabic',
'Uyghur',
'Min Dong Chinese',
'Sylheti'
];